
export const FETCH_JOKE_BY_ID_REQUESTED = 'FETCH_JOKE_BY_ID_REQUESTED';
export const FETCH_JOKE_BY_ID_SUCCESSED = 'FETCH_JOKE_BY_ID_SUCCESSED';
export const FOUND_AN_ERROR = 'FOUND_AN_ERROR';

export const FETCH_ALL_JOKES_REQUESTED = 'FETCH_ALL_JOKES_REQUESTED';
export const FETCH_ALL_JOKES_SUCCESSED = 'FETCH_ALL_JOKES_SUCCESSED';


